[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate"]

[start]
cmd = "echo '[DEPLOY] running prisma db push...' && npx prisma db push --accept-data-loss --skip-generate && echo '[DEPLOY] db push OK' && node src/index.js"
